version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amdocschatbot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: streamlit_app
    restart: always
    depends_on:
      - db
    ports:
      - "8501:8501"
    environment:
      DATABASE_URL: postgresql://chatuser:password@db/amdocschatbot
      HUGGINGFACE_API_KEY: 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
    volumes:
      - .:/app
    command: ["streamlit", "run", "file.py"]

volumes:
  postgres_data:
